apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workshop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-workshop-app
  template:
    metadata:
      labels:
        app: k8s-workshop-app
    spec:
      containers:
        - name: blabs-k8s-workshop
          image: blabs-k8s-workshop
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 3
