apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-workshop-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-workshop-app
  template:
    metadata:
      labels:
        app: k8s-workshop-app
    spec:
      containers:
        - name: blabs-k8s-workshop
          image: blabs-k8s-workshop
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
