apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop-service
spec:
  selector:
    app: k8s-workshop-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
